### ISSUE TITLE
Set different buffer radius for mesh and cameras

### ISSUE THREAD

**Issue by russelldj** [open-forest-observatory/multiview-tree-species-classification-experiments#1]
Currently we use the same 50m radius buffer to subset both the mesh and the camera set. This should be updated to have a smaller radius for the mesh and a larger one for the cameras. The mesh buffer only needs to be large enough to be reasonably confident that occlusion reasoning can happen. Importantly, decreasing the size of the mesh results in faster rendering/aggregation. A radius of 25m is probably sufficient. However, the camera set buffer should include all cameras that can observe the labeled regions. This is likely on the order of 100m for these scenes.

**Comment by mikoontz** [comment]
In case useful, the DJI Zenmuse X3 camera has a ground footprint on flat ground of 205.667m horizontally by 151.667 m vertically when flying at 120m. The hypotenuse of that is 255.5417 m, and half of that (the distance between where the camera is and the corners, ignoring height) is 127.7708 m (`sqrt(205.667^2 + 151.667^2) / 2`). If you also need to include height for that distance, then the actual camera to far corner distance is 175.28m (`sqrt(120^2 + (sqrt(205.667^2 + 151.667^2) / 2)^2)`)

I believe the more recent DJI cameras have a slightly narrower field of view so the calculations above would be conservative for more modern use cases. If there's a downhill slope though, then the camera might be able to see labeled regions a little further.
